version: '3.8'

services:
  movie-list-front:
    container_name: movie-list-front
    build:
      context: ./movie-list-front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    # environment:
    #   NODE_ENV: development
    # volumes:
    #   - ./movie-list-front:/app
    #   - /app/node_modules
    depends_on:
      - movie-api

  mongo-local:
    image: mongo:latest
    container_name: mongo-local
    ports:
      - "27017:27017"
    volumes:
      # - mongo-local-data:/data/db #for persistance
      - ./mongo-init:/docker-entrypoint-initdb.d

  movie-api:
    image: movie-api:latest
    build: ./movie-api
    container_name: movie-api
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
    depends_on:
      - mongo-local

# volumes:  #for persistance
#   mongo-local-data: